### ISSUE TITLE
[Bug] Can not document CompositionView in Blueprint

### ISSUE THREAD

**Issue by chenjr0719** [sanic-org/sanic-openapi#108]
**Describe the bug**
I found this bug when I add new test cases. Can not document `CompositionView` in Blueprint.

**Screenshots**
When put `CompositionView` in the app:
![image](https://user-images.githubusercontent.com/13619684/59170742-9ee74500-8b72-11e9-8724-058cc9ac38ee.png)
As you can see, the `CompositionView` can be documented in the app.

And put `CompositionView` in blueprint:
![image](https://user-images.githubusercontent.com/13619684/59170788-c9d19900-8b72-11e9-808a-fe64caec60b3.png)
The tags of blueprint will be created but no path in this tag.

**To Reproduce**
```python
from sanic import Blueprint, Sanic
from sanic.response import text
from sanic.views import CompositionView

from sanic_openapi import swagger_blueprint

app = Sanic()
app.blueprint(swagger_blueprint)

bp = Blueprint("bp")
app.blueprint(bp)


def get_handler(request):
    return text("I am a get method")


view = CompositionView()
view.add(["GET"], get_handler)
view.add(["POST", "PUT"], lambda request: text("I am a post/put method"))

# app.add_route(view, "/") # uncomment this line to see how CompositionView works in app
bp.add_route(view, "/")


app.run()

```

**Expected behavior**
The routes of `CompositionView` in blueprint should be documented at swagger.

**Environment (please complete the following information):**
 - OS: [Ubuntu 18.04]
 - Browser [firefox]
 - Version [[master](https://github.com/huge-success/sanic-openapi/commit/c10d71e3c0705a7a2fb8aff76423faadd89d86e5)]

**Additional context**
Looks likes we have to add some `if` statement to handle `CompositionView` in blueprint at:
https://github.com/huge-success/sanic-openapi/blob/c10d71e3c0705a7a2fb8aff76423faadd89d86e5/sanic_openapi/swagger.py#L79-L96

**Comment by artcg** [comment]
The code in this example doesnt create any routes (`app.router.routes_all.items()` doesnt contain anything except swagger stuff, and the GET route for example does not work) so if there is a bug here it is to do with sanic, not sanic-openapi
