### ISSUE TITLE
[Bug] API can't show the document for query parameters when defined in class

### ISSUE THREAD

**Issue by pansila** [sanic-org/sanic-openapi#195]
**Describe the bug**
Parameters are defined in the class and used in the location of 'query', but the the web page doesn't show them instead of an empty 'body' item. Parameters in the location of 'body' are fine.

**Screenshots**
1. can't see the document in the web page.
![image](https://user-images.githubusercontent.com/5125601/102774386-d5d42300-43c5-11eb-9b55-55d613dc1934.png)
2. can see the definitions are correct in the swagger.json
![image](https://user-images.githubusercontent.com/5125601/102774415-e4223f00-43c5-11eb-9f49-52ec450fe14f.png)

**To Reproduce**
```
class endpoint_query:
    page = doc.Integer(description='The page number of the whole test report list') #default=1, 
    limit = doc.Integer(description='The item number of a page') #default=10, 
    title = doc.String(description='The test suite name')
    forbidden = doc.String(description='Get endpoints that are forbidden to connect')
    unauthorized = doc.String(description='Get endpoints that have not authorized to connect')

@doc.consumes(_endpoint_query)  # TODO: bug, can't show the doc when using it like this
def handler(reqeust):
    ...
```

**Expected behavior**
Can see the document in the web page

**Environment (please complete the following information):**
 - OS: [Windows 10 64bit]
 - Browser [chrome 87]
 - Version [0.6.1]

**Additional context**
None

**Comment by pansila** [comment]
The issue is also seen for the location of 'formData'

**Comment by artcg** [comment]
schema is not supported in openAPI2 for query parameters, that is why, see https://swagger.io/specification/v2/ for more info
