### ISSUE TITLE
OpenAPI 3.0 spec

### ISSUE THREAD

**Issue by sdorgancs** [sanic-org/sanic-openapi#196]
Do you plan to implement Open API 3.0 Spec?

**Comment by ruckc** [comment]
@sdorgancs we have the #194 PR in with the changes necessary for it, just waiting on owners to review/merge.

**Comment by ahopkins** [comment]
I think @chenjr0719 is no longer active, and I'm here only for admin. I'm looking for some help in taking this and driving the project.

**Comment by ruckc** [comment]
@ahopkins i can help test/ensure it works for my use case, but beyond that i'm not sure what i can do maybe @ioggstream can help given the work he did for OpenAPI spec 3.0

**Comment by artcg** [comment]
Closed in #210
