### ISSUE TITLE
[Bug] Query Parameter of Type List incompatible with sanic

### ISSUE THREAD

**Issue by sbutz** [sanic-org/sanic-openapi#199]
**Description**
A clear and concise description of what the bug is. It there is error log, please provide it.
Declaring a query parameter of type List (see example below) is not parsed correctly by sanic RequestParameters.getlist().

```
@app.route("/")
@doc.consumes(doc.List(name='foo'), location='query')
async def root(request):
    foo = request.args.getlist('foo') # ['foo,bar,bob'] instead of ['foo', 'bar', 'bob']
```

The swagger ui proposes for inputing 1 and 2 for the parameter foo the following curl command:
```
http://localhost:8000/?foo=1,2
```
```
    foo = request.args.getlist('foo') # ['1,2'] instead of ['1', '2']
```

**Expected behavior**
The default behaviour of sanic-openapi should be parsable by sanic.

**Environment**
 - OS: Debian Buster
 - Browser Firefox 78.7.0esr
 - Version 0.6.2

**Proposed fix**
```
diff --git a/sanic_openapi/doc.py b/sanic_openapi/doc.py
index cf255d9..016d82c 100644
--- a/sanic_openapi/doc.py
+++ b/sanic_openapi/doc.py
@@ -111,7 +111,7 @@ class List(Field):
             items = serialize_schema(self.items[0])
         else:
             items = []
-        return {"type": "array", "items": items, **super().serialize()}
+  

      return {"type": "array", "collectionFormat": "multi", "items": items, **super().serialize()}

class UUID(Field):
 ```

**Comment by artcg** [comment]
I disagree that this a bug, since I think most people specifying a "list" would expect the default "csv" collectionFormat behaviour, however, would be open to a PR making this a keyword argument 

The sanic request.getlist is unrelated to the naming of doc.List, just so happens to crossover
