### ISSUE TITLE
does not produce the doc for this end point

### ISSUE THREAD

**Issue by kporika** [sanic-org/sanic-openapi#200]
@doc.consumes({'Authorization': str}, location='header')
@scoped('admin')
@doc.consumes(
    {"view":
            {
                "username": str,
                "password" :str,
                "email" : str,
                "first_name": str,
                "last_name" : str,
                "is_superuser" : bool
            }
    }, 
location="body")
async def add_user(request):
sanic==20.12.1
sanic-jwt==1.6.0
sanic-openapi==0.6.2
on python3.9

it only produces authorization doc, but not for body
![Screen Shot 2021-02-09 at 3 41 23 PM](https://user-images.githubusercontent.com/7038720/107425701-51606f80-6aed-11eb-8549-a83cdd904f21.png)

**Comment by artcg** [comment]
Please put code tags around the code so that your issue displays better

**Comment by purbano-cardano** [comment]
It's because you're using a decorator @Scoped, and everything after that gets out of doc. I'm facing the same problem.
