### ISSUE TITLE
[Bug] Swagger validation error: consumes. is not of type `string`

### ISSUE THREAD

**Issue by jacebrowning** [sanic-org/sanic-openapi#209]
**Describe the bug**

Documenting query parameters following the provided examples results in a Swagger validation error.

**To Reproduce**

Define a route similar to [this](https://sanic-openapi.readthedocs.io/en/stable/sanic_openapi/decorators.html#query) example:

```python
@app.get("/test")
@doc.consumes(doc.String(name="filter"), location="query")
async def test(request):
    return json({"Hello": "World"})
```

**Expected behavior**

This route should pass Swagger validation, but it does not, resulting in an error similar to the following:

```json
{
  "messages": [
    "attribute paths.'/test'(get).consumes. is not of type `string`"
  ],
  "schemaValidationMessages": [
    {
      "level": "error",
      "domain": "validation",
      "keyword": "allOf",
      "message": "instance failed to match all required schemas (matched only 0 out of 1)",
      "schema": {
        "loadingURI": "http://swagger.io/v2/schema.json#",
        "pointer": "/definitions/operation/properties/consumes"
      },
      "instance": {
        "pointer": "/paths/~1test/get/consumes"
      }
    }
  ]
}
```

**Additional context**

The error is fixed by including a content type:

```python
@doc.consumes(doc.String(name="filter"), content_type="text/plain", location="query")
```

I propose this should either be called out in the documentation or made the default for `location="query"`.

**Comment by artcg** [comment]
Should be fixed in https://github.com/sanic-org/sanic-openapi/pull/198, though that suggests "application/json" as a default, does that work for you?

**Comment by jacebrowning** [comment]
Yeah, "application/json" seems to pass validation and the Swagger UI works as expected: https://github.com/jacebrowning/memegen/pull/603

**Comment by ahopkins** [comment]
Can we close?

**Comment by jacebrowning** [comment]
Yeah, I think so. A `0.6.x` release would be appreciated!
