### ISSUE TITLE
Oh, that's bullshit! It's too bad that my project is criticized by my leaders every day because of its running problems

### ISSUE THREAD

**Issue by liukaiyang931** [sanic-org/sanic-openapi#224]
Oh, that's bullshit! It's too bad that my project is criticized by my leaders every day because of its running problems

**Comment by ahopkins** [comment]
What is this in reference to? We would appreciate refraining from the usage of such language. Is there a constructive conversation that you would like to have, I am happy to engage.

**Comment by liukaiyang931** [comment]
When I add this library to my sanic project, my project will not work normally. I guess it is because I use Linux system, because I can work normally in win10 system

**Comment by ahopkins** [comment]
If you would like some support from one of the volunteers that has built this platform or Sanic entirely in their free time, then I suggest you provide a more helpful message. There is no one that can attempt to assist you with what you have provided. If you would like someone to assist, or, if you believe you have found a bug, then by all means raise an issue and maybe someone will help.
