### ISSUE TITLE
can not import openapi2_blueprint from sanic_openapi

### ISSUE THREAD

**Issue by BadReese** [sanic-org/sanic-openapi#227]
**Describe the bug**
can not import openapi2_blueprint from sanic_openapi, why?

**Screenshots**
`from sanic_openapi import openapi2_blueprint
ImportError: cannot import name 'openapi2_blueprint' from 'sanic_openapi' (/Users//miniconda3/envs/demo/lib/python3.8/site-packages/sanic_openapi/__init__.py)
`

**To Reproduce**
Your code snippet or steps to reproduce the bug.

**Expected behavior**

**Environment (please complete the following information):**
 - OS: mac
 - Browser chrome
 - Version python 3.8.8

**Additional context**
Add any other context about the problem here. This might be how to fix this bug or some hint to fix it.

**Comment by ahopkins** [comment]
There's a bunch of changes that need to be released. Probably this weekend.

**Comment by chenshigithub** [comment]
from .openapi2 import doc, openapi2_blueprint
ModuleNotFoundError: No module named 'sanic_openapi.openapi2'
