### ISSUE TITLE
Method POST not allowed for URL

### ISSUE THREAD

**Issue by snakecy** [sanic-org/sanic-openapi#238]
**Describe the bug**
A clear and concise description of what the bug is. It there is error log, please provide it.

**Screenshots**
The screenshots of Swagger UI if this bug is related to it.
![image](https://user-images.githubusercontent.com/12490881/123744824-e79d0280-d8e1-11eb-9a1d-f974a4746bf8.png)

**To Reproduce**
Your code snippet or steps to reproduce the bug.

**Expected behavior**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Browser [e.g. chrome, firefox]
 - Version [e.g. 0.5.3]

**Additional context**
Add any other context about the problem here. This might be how to fix this bug or some hint to fix it.

**Comment by ahopkins** [comment]
Can you please post the version of: `sanic`, `sanic-routing`, and `sanic-openapi` that you have installed? Also, do you have a snippet of code for the route?

**Comment by artcg** [comment]
Please also add the expected behaviour as it is unclear to me what this screenshot is referring to
