### ISSUE TITLE
Can't handle duplicate path

### ISSUE THREAD

**Issue by koug44** [sanic-org/sanic-openapi#239]
Here is the simple bug to show the bug. Sanic server has two handlers having the same path:

```
from sanic import Sanic
from sanic.response import json
from sanic_openapi import openapi2_blueprint

app = Sanic(name="AwesomeApi")
app.blueprint(openapi2_blueprint)


@app.get("/path")
async def test(request):
    return json({"hello": "world"})


@app.post("/path")
async def post_test(request):
    return json({"hello": "world"})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
```

Swagger doc only includes one handler

![image](https://user-images.githubusercontent.com/4643678/124977941-224c1c80-dfff-11eb-9808-de02b006d052.png)

**Comment by artcg** [comment]
Thanks for the report, will check that out over next couple days
