### ISSUE TITLE
[Feature Request] Custom Ordering of Endpoints and Authorization

### ISSUE THREAD

**Issue by amit-d-bahir** [sanic-org/sanic-openapi#245]
**Is your feature request related to a problem? Please describe your use case.**

-  Is there a way in which I can give an ordering in which the endpoints are displayed on the UI? I just want to have one endpoint at the top always.
- Is there any way in which I can provide an argument in a decorator  so that a particular endpoint does not have authorization enabled (i.e the padlock icon is not shown)

**Describe the solution you'd like**
For ordering, if I can give priority as topmost then it will always be on the top.
For authorization, adding a decorator that excludes_authorization.

**Comment by ahopkins** [comment]
You can control this with tags. They should appear in the order in which the tags are created.

**Comment by amit-d-bahir** [comment]
I am able to group the endpoints using a tag. But the order in which those endpoints occur on the UI is random. 
Is there any way I can have a particular tag always on top?

**Comment by ahopkins** [comment]
You can customize with the [Swagger config](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/)

```python
app.config.SWAGGER_UI_CONFIGURATION = {
    "operationsSorter": "method",
}
```

Sounds like for your need, you might need to pass a function, which can only be done in the JS. I am not sure there is a good way to do that just now.

**Comment by ahopkins** [comment]
To be :100: honest, it is not likely to be a feature that will be added to this package. I am actively working on [sanic-ext](https://github.com/sanic-org/sanic-ext) [Read more](https://community.sanicframework.org/t/openapi-next-generation-with-built-in-validation/843). Having more control over the static assets will be something available there, and should be a near drop-in replacement for `sanic-openapi` (at least for OAS3, we are dropping the `@doc` and OAS2).
