### ISSUE TITLE
[Feature Request] Create new Release for Sanic 21.12.0

### ISSUE THREAD

**Issue by morph027** [sanic-org/sanic-openapi#254]
**Is your feature request related to a problem? Please describe your use case.**
Right now, i'm unable to use sanic-openapi with Sanic 21.12.0 via pip due to https://github.com/sanic-org/sanic-openapi/pull/253

**Describe the solution you'd like**
Please create a new release on pypi. I can add a PR for this, but was unsure about the version (21.12.0 or 22.1.1?).

**Comment by ahopkins** [comment]
It should be versioned 21.12. TY.

**Comment by morph027** [comment]
Happy to help ;)

PR in #255
